version: "2"

# Servers
services:
  install_plugins:
    restart: never
    build:
      context: .
      dockerfile: sonarqube-plugins.Dockerfile
    volumes:
      - sonarqube6_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube:
    image: sonarqube:6.0
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar?user=sonar&password=sonar
    volumes:
      - sonarqube6_conf:/opt/sonarqube/conf
      - sonarqube6_data:/opt/sonarqube/data
      - sonarqube6_extensions:/opt/sonarqube/extensions
      - sonarqube6_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql6:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql6_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube6_conf:
  sonarqube6_data:
  sonarqube6_extensions:
  sonarqube6_bundled-plugins:
  postgresql6:
  postgresql6_data:
